### ISSUE TITLE
Error when using setInterval() in onReadRequest

### ISSUE THREAD

**Issue by Kerdanyy** [sandeepmistry/bleno#183]
Hey,

I can trigger “onReadRequest” successfully on the edison sending only once to the android , The problem I have is in sending a reply to the android each sec using the interval () function (after triggering onReadRequest once), is it possible to do it in the onReadRequest?

onReadRequest : function(offset, callback) {
console.log(“Read request received”);
this.intervalId = setInterval(function() {
callback(new Buffer(“Hi!”));
}, 1000);
},

when I use the above code, I get the following error 

TypeError: value is out of bounds
at TypeError ()
at checkInt (buffer.js:705:11)
at Buffer.writeUInt8 (buffer.js:715:5)
at Gatt.errorResponse (/home/root/node_modules/bleno/lib/hci-socket/gatt.js:293:7)
at null. (/home/root/node_modules/bleno/lib/hci-socket/gatt.js:730:35)
at null. (/home/root/Echo10.js:82:30)
at wrapper [as _onTimeout] (timers.js:261:14)
at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

Thank you

**Comment by sandeepmistry** [comment]
@Kerdanyy the callback can only be called once for a read request.

It sounds like you want to use a notify characteristic instead. See: https://github.com/sandeepmistry/bleno/blob/master/test.js#L101-L126
