### ISSUE TITLE
bleno error on raspberry pi3 platfrom

### ISSUE THREAD

**Issue by Arun22** [sandeepmistry/bleno#188]
I was trying to execute the main.js from example/echo in rasp 3.0 hardware. after I install the node source package as per the instruction from "https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions". 

I got some exception on debug module not found error: I am kind of new to Java Script. if this issue is something basic, please bare with me. Thanks

pi@raspberrypi:~/project/bleno/bleno/examples/echo$ node main.js
module.js:341
    throw err;
    ^

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/pi/project/bleno/bleno/lib/bleno.js:1:75)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

**Comment by Arun22** [comment]
I just figured out: I need to install the dependency through npm. sorry for false alarm. 

pi@raspberrypi:~/project/bleno/bleno$ npm ls
bleno@0.4.0 /home/pi/project/bleno/bleno
├── UNMET OPTIONAL DEPENDENCY bluetooth-hci-socket@~0.4.3
├── UNMET OPTIONAL DEPENDENCY bplist-parser@0.0.6
├─┬ debug@2.2.0
│ └── ms@0.7.1
└── UNMET OPTIONAL DEPENDENCY xpc-connection@~0.1.4
