### ISSUE TITLE
Tessel 2 - Not working

### ISSUE THREAD

**Issue by julesmoretti** [sandeepmistry/bleno#271]
So I am trying to get this code running:

`npm install bleno --force`

```
var bleno = require('bleno');

bleno.on('stateChange', function(state) {
  console.log('on -> stateChange: ' + state);

  if (state === 'poweredOn') {
    bleno.startAdvertising('Battery', 'fffffffffffffffffffffffffffffff0');
  } else {
    bleno.stopAdvertising();
  }
});

bleno.on('advertisingStart', function(error) {
  console.log('on -> advertisingStart: ' + (error ? 'error ' + error : 'success'));
});
console.log('waiting for power up...');
```

I get the following:

```
buffer.js:631
        return this.hexWrite(string, offset, length);
                    ^

TypeError: Invalid hex string
    at TypeError (native)
    at Buffer.write (buffer.js:631:21)
    at fromString (buffer.js:173:26)
    at new Buffer (buffer.js:61:12)
    at e.startAdvertising (/tmp/remote-script/node_modules/bleno/lib/hci-socket/gap.js:1:966)
    at u.startAdvertising (/tmp/remote-script/node_modules/bleno/lib/hci-socket/bindings.js:1:520)
    at e.startAdvertising (/tmp/remote-script/node_modules/bleno/lib/bleno.js:1:2139)
    at e.<anonymous> (/tmp/remote-script/index.js:1:172)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)

```

How can I set custom uuid?

**Comment by julesmoretti** [comment]
It needed to be an array:
`bleno.startAdvertising('Battery', ['fffffffffffffffffffffffffffffff0']);`
