### ISSUE TITLE
bleno install errors on raspberry pi 3 model B

### ISSUE THREAD

**Issue by cmoulikus** [sandeepmistry/bleno#334]
Hi

I have pi version 3 model B running Jessie release 8.0. I have node version 5.9.1 and npm version 3.7.3 I get the following errors when I run

 sudo npm install bleno

usb@1.2.0 install /home/pi/Bluetooth/node_modules/usb
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://github.com/tessel/node-usb/releases/download/1.2.0/usb_bindings-v1.2.0-node-v47-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for usb@1.2.0 and node@5.9.1 (node-v47 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.9.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/Bluetooth/node_modules/usb/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: certificate is not yet valid
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1065:38)
gyp ERR! stack     at emitNone (events.js:80:13)
gyp ERR! stack     at TLSSocket.emit (events.js:179:7)
gyp ERR! stack     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:593:8)
gyp ERR! stack     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:425:38)
gyp ERR! System Linux 4.4.11-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/pi/Bluetooth/node_modules/usb/src/binding/usb_bindings.node" "--module_name=usb_bindings" "--module_path=/home/pi/Bluetooth/node_modules/usb/src/binding"
gyp ERR! cwd /home/pi/Bluetooth/node_modules/usb
gyp ERR! node -v v5.9.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/Bluetooth/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/home/pi/Bluetooth/node_modules/usb/src/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/Bluetooth/node_modules/usb/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:100:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Linux 4.4.11-v7+
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/pi/Bluetooth/node_modules/usb/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/Bluetooth/node_modules/usb
node-pre-gyp ERR! node -v v5.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/Bluetooth/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/home/pi/Bluetooth/node_modules/usb/src/binding' (1)
npm WARN install:usb@1.2.0 usb@1.2.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:usb@1.2.0 Exit status 1

> bluetooth-hci-socket@0.5.1 install /home/pi/Bluetooth/node_modules/bluetooth-hci-socket
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.9.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/Bluetooth/node_modules/bluetooth-hci-socket/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: certificate is not yet valid
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1065:38)
gyp ERR! stack     at emitNone (events.js:80:13)
gyp ERR! stack     at TLSSocket.emit (events.js:179:7)
gyp ERR! stack     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:593:8)
gyp ERR! stack     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:425:38)
gyp ERR! System Linux 4.4.11-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/Bluetooth/node_modules/bluetooth-hci-socket
gyp ERR! node -v v5.9.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
npm WARN install:bluetooth-hci-socket@0.5.1 bluetooth-hci-socket@0.5.1 install: `node-gyp rebuild`
npm WARN install:bluetooth-hci-socket@0.5.1 Exit status 1
/home/pi/Bluetooth
└─┬ bleno@0.4.2 
  ├── bplist-parser@0.0.6 
  └─┬ debug@2.6.8 
    └── ms@2.0.0 

npm WARN optional Skipping failed optional dependency /bleno/xpc-connection:
npm WARN notsup Not compatible with your operating system or architecture: xpc-connection@0.1.4
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/Bluetooth/package.json'
npm WARN Bluetooth No description
npm WARN Bluetooth No repository field.
npm WARN Bluetooth No README data
npm WARN Bluetooth No license field.

**Comment by cmoulikus** [comment]
Installed successfully after doing sudo apt-get upgrade and doing npm install bleno
Closing
