### ISSUE TITLE
Crash on bonding

### ISSUE THREAD

**Issue by skirge** [sandeepmistry/bleno#345]
Executed option "Bond" on Bleno device in nRF Connect.
Following stacktrace appears

```
PROJECT/node_modules/bleno/lib/hci-socket/crypto.js:60
  var output = new Buffer(input.length);
                               ^

TypeError: Cannot read property 'length' of undefined
    at swap (PROJECT/node_modules/bleno/lib/hci-socket/crypto.js:60:32)
    at e (PROJECT/node_modules/bleno/lib/hci-socket/crypto.js:37:9)
    at Object.c1 (PROJECT/node_modules/bleno/lib/hci-socket/crypto.js:22:9)
    at Smp.handlePairingRandom (PROJECT/node_modules/bleno/lib/hci-socket/smp.js:130:12)
    at Smp.onAclStreamData (PROJECT/node_modules/bleno/lib/hci-socket/smp.js:58:10)
    at emitTwo (events.js:92:20)
    at emit (events.js:172:7)
    at AclStream.push (PROJECT/node_modules/bleno/lib/hci-socket/acl-stream.js:26:10)
    at BlenoBindings.onAclDataPkt (PROJECT/node_modules/bleno/lib/hci-socket/bindings.js:201:21)
    at emitThree (events.js:97:13)
```

**Comment by jackdneilson** [comment]
In smp.js, if handlePairingRandom() is called this._tk is not set leading to the undefined pointer.
