### ISSUE TITLE
Error on Catalina when using library,

### ISSUE THREAD

**Issue by ghost** [sandeepmistry/bleno#447]
I'm currently using OS X Catalina
When running var blue = require("bluetooth") I get the following error 
Thrown:
Error: Cannot find module 'xpc-connection'
Require stack:
- /Users/chris/node_modules/bleno/lib/mac/highsierra.js
- /Users/chris/node_modules/bleno/lib/mac/bindings.js
- /Users/chris/node_modules/bleno/lib/bleno.js
- /Users/chris/node_modules/bleno/index.js
- <repl>
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/chris/node_modules/bleno/lib/mac/highsierra.js',
    '/Users/chris/node_modules/bleno/lib/mac/bindings.js',
    '/Users/chris/node_modules/bleno/lib/bleno.js',
    '/Users/chris/node_modules/bleno/index.js',
    '<repl>'
  ]
}

**Comment by animaonline** [comment]
Seems like this project is dead.

**Comment by rzr** [comment]
May I suggest to try @abandonware fork and report at:
Relate-to: https://github.com/abandonware/bleno/issues/17
